### Login
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "Parisma@gmail.com",
  "password": "22222222"
}

###
GET http://localhost:3000/user/device/2/control-unit/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI3MzE4NzEsImV4cCI6MTcxMjczNTQ3MSwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.CZLCnpqh6hZDJA4RBukJI6Qa8BgGel946HhyYsCf08k

###
POST http://localhost:3000/user/device/2/control-unit/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI3MzE4NzEsImV4cCI6MTcxMjczNTQ3MSwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.CZLCnpqh6hZDJA4RBukJI6Qa8BgGel946HhyYsCf08k
Content-Type: application/json

{
    "StockId": 5
}
###
GET http://localhost:3000/user/device/14/control-unit/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI3MzE4NzEsImV4cCI6MTcxMjczNTQ3MSwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.CZLCnpqh6hZDJA4RBukJI6Qa8BgGel946HhyYsCf08k
###
PATCH http://localhost:3000/user/device/14/control-unit/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI3MzE4NzEsImV4cCI6MTcxMjczNTQ3MSwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.CZLCnpqh6hZDJA4RBukJI6Qa8BgGel946HhyYsCf08k

{
  "name": "LED buld"
}

###
DELETE http://localhost:3000/user/device/14/control-unit/26 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI3MzE4NzEsImV4cCI6MTcxMjczNTQ3MSwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.CZLCnpqh6hZDJA4RBukJI6Qa8BgGel946HhyYsCf08k
