### Login
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "Parisma@gmail.com",
  "password": "22222222"
}

###
GET http://localhost:3000/user/device/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI1NDYxMzAsImV4cCI6MTcxMjU0OTczMCwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.i3C6ruw_R6nl38STjXIf5hp6ef1STbJ0t_DnMm7M7YQ

###
GET http://localhost:3000/user/device/14 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI1NDYxMzAsImV4cCI6MTcxMjU0OTczMCwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.i3C6ruw_R6nl38STjXIf5hp6ef1STbJ0t_DnMm7M7YQ

###
POST http://localhost:3000/user/device/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI1NDYxMzAsImV4cCI6MTcxMjU0OTczMCwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.i3C6ruw_R6nl38STjXIf5hp6ef1STbJ0t_DnMm7M7YQ

{
    "StockId": 1
}

###
PATCH http://localhost:3000/user/device/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI1NDYxMzAsImV4cCI6MTcxMjU0OTczMCwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.i3C6ruw_R6nl38STjXIf5hp6ef1STbJ0t_DnMm7M7YQ

{
  "BSmode": "schedule"
}

###
DELETE http://localhost:3000/user/device/12 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI1NDYxMzAsImV4cCI6MTcxMjU0OTczMCwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.i3C6ruw_R6nl38STjXIf5hp6ef1STbJ0t_DnMm7M7YQ


