### Payload
GET http://localhost:3000/test/payload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTIyMjg3ODEsImV4cCI6MTcxMjIzMjM4MSwiYXVkIjoiOTA0ZjcyM2QtMzlmYS00ZmI0LTkyNGUtMjUzODJmNTEzMzMyIiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.zHauqP6OZ6ON_QmCRS094-Z3PlBvR5xTf2AtdO94FBM

### User in request
GET http://localhost:3000/test/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTIyNDYwNDYsImV4cCI6MTcxMjI0OTY0NiwiYXVkIjoiOTA0ZjcyM2QtMzlmYS00ZmI0LTkyNGUtMjUzODJmNTEzMzMyIiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.lXuZJQgKM5QXB6DCS7D_Ip06fIqhttVxCUrwq7j1IY4

### Inside a user object
GET http://localhost:3000/test/user/inside
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTIzODU2OTMsImV4cCI6MTcxMjM4OTI5MywiYXVkIjoiOTA0ZjcyM2QtMzlmYS00ZmI0LTkyNGUtMjUzODJmNTEzMzMyIiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.jNbuvigmxypuQwv4IVZ4VCyFLcdvkx1wM6X8p0jRX0c
