### Login User
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "Parisma@gmail.com",
  "password": "22222222"
}

###
GET http://localhost:3000/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiUGFyaXNtYSIsImZpcnN0TmFtZSI6Ikpha2hpc2hhbWlzIiwibGFzdE5hbWUiOiJQYXJpc21hIiwiYXZhdGFyVXJsIjpudWxsLCJpYXQiOjE3MTI3MzU2NjQsImV4cCI6MTcxMjczOTI2NCwiYXVkIjoiOWFjODU4NTMtZGJkMC00NjM1LWFjNTYtNDlmMjczMjcxYzA1IiwiaXNzIjoibWluaWdhcmRlbi5jb20ifQ.pdGOOEAJ2400ae-QCib0MChAjviRl_otXj8bGs-xmkc

###
PATCH http://localhost:3000/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiSm9obkRvZSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsImF2YXRhclVybCI6bnVsbCwiaWF0IjoxNzEyNjM1NDQyLCJleHAiOjE3MTI2MzkwNDIsImF1ZCI6IjBlYjhjZWYyLWQ0NDctNGYzNy04YTEyLTg0NjVmNzc0NTE4MyIsImlzcyI6Im1pbmlnYXJkZW4uY29tIn0.lau8TBGdSzN88XvwJaE900PykipbeixmPx1Wgr1eb6I
Content-Type: application/json

{
    "postalCode": "70001",
    "bio": "I'm a developer who loves seeing lovers!"
}

###
DELETE http://localhost:3000/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiSm9obkRvZSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsImF2YXRhclVybCI6bnVsbCwiaWF0IjoxNzEyNjM1NDQyLCJleHAiOjE3MTI2MzkwNDIsImF1ZCI6IjBlYjhjZWYyLWQ0NDctNGYzNy04YTEyLTg0NjVmNzc0NTE4MyIsImlzcyI6Im1pbmlnYXJkZW4uY29tIn0.lau8TBGdSzN88XvwJaE900PykipbeixmPx1Wgr1eb6I
